"use client";

import React, { useRef, useState } from "react";
import { X, Download, FileText, Printer, ZoomIn, ZoomOut, Clock } from "lucide-react";
import jsPDF from "jspdf";
import { MarkdownOutput } from "./markdown-output";

interface DocumentPreviewProps {
    isOpen: boolean;
    onClose: () => void;
    title: string;
    content: string;
    agentName: string;
    agentRole: string;
    timestamp: Date;
}

export function DocumentPreview({
    isOpen,
    onClose,
    title,
    content,
    agentName,
    agentRole,
    timestamp
}: DocumentPreviewProps) {
    const docRef = useRef<HTMLDivElement>(null);
    const [isExporting, setIsExporting] = useState(false);
    const [zoom, setZoom] = useState(1);

    if (!isOpen) return null;

    const handleExportPDF = () => {
        setIsExporting(true);
        try {
            const doc = new jsPDF({ format: "a4", unit: "mm" });
            const margin = 18;
            const pageW = doc.internal.pageSize.getWidth() - margin * 2;
            const pageH = doc.internal.pageSize.getHeight();
            let y = 20;

            const addPageIfNeeded = (needed = 8) => {
                if (y + needed > pageH - 18) { doc.addPage(); y = 20; }
            };

            // ── Header ──
            doc.setFillColor(22, 33, 30);
            doc.rect(0, 0, doc.internal.pageSize.getWidth(), 30, "F");
            doc.setFont("helvetica", "bold");
            doc.setFontSize(18);
            doc.setTextColor(212, 175, 55); // Gold
            doc.text("SUTRADHAR.AI", margin, 14);
            doc.setFontSize(8);
            doc.setTextColor(156, 163, 175);
            doc.text("Official Document", margin, 20);
            doc.setFontSize(9);
            doc.setTextColor(230, 230, 230);
            doc.text(`Agent: ${agentName}  ·  Role: ${agentRole}`, margin, 27);
            y = 42;

            // ── Title ──
            doc.setFont("helvetica", "bold");
            doc.setFontSize(16);
            doc.setTextColor(160, 120, 20); // Dark gold — readable on white
            addPageIfNeeded(14);
            doc.text(doc.splitTextToSize(title, pageW), margin, y);
            y += 10;
            doc.setDrawColor(160, 120, 20);
            doc.setLineWidth(0.4);
            doc.line(margin, y, margin + pageW, y);
            y += 8;

            // ── Content ──
            const rawLines = content
                .replace(/^#{1,3}\s+(.+)/gm, "## $1")  // keep heading markers as signals
                .split("\n");

            for (const raw of rawLines) {
                const line = raw.trim();
                if (!line) { y += 3; continue; }

                if (line.startsWith("## ")) {
                    addPageIfNeeded(12);
                    doc.setFont("helvetica", "bold");
                    doc.setFontSize(12);
                    doc.setTextColor(160, 120, 20); // Dark gold — readable on white
                    const wrapped = doc.splitTextToSize(line.replace(/^## /, ""), pageW);
                    doc.text(wrapped, margin, y);
                    y += wrapped.length * 6 + 2;
                } else if (line.startsWith("- ") || line.startsWith("* ")) {
                    addPageIfNeeded(7);
                    doc.setFont("helvetica", "normal");
                    doc.setFontSize(10);
                    doc.setTextColor(30, 30, 30); // Near black
                    const bullet = "•  " + line.replace(/^[-*]\s/, "").replace(/\*\*(.*?)\*\*/g, "$1");
                    const wrapped = doc.splitTextToSize(bullet, pageW - 4);
                    doc.text(wrapped, margin + 2, y);
                    y += wrapped.length * 5.5 + 1;
                } else {
                    addPageIfNeeded(7);
                    doc.setFont("helvetica", "normal");
                    doc.setFontSize(10);
                    doc.setTextColor(30, 30, 30); // Near black — readable on white
                    const clean = line.replace(/\*\*(.*?)\*\*/g, "$1").replace(/\*(.*?)\*/g, "$1").replace(/`(.*?)`/g, "$1");
                    const wrapped = doc.splitTextToSize(clean, pageW);
                    doc.text(wrapped, margin, y);
                    y += wrapped.length * 5.5 + 1;
                }
            }

            // ── Footer on last page ──
            const totalPages = (doc as any).internal.getNumberOfPages();
            for (let i = 1; i <= totalPages; i++) {
                doc.setPage(i);
                doc.setFont("helvetica", "italic");
                doc.setFontSize(7);
                doc.setTextColor(107, 114, 128);
                doc.text(
                    `Generated by Sutradhar.AI  ·  ${new Date(timestamp).toLocaleString()}  ·  Page ${i} of ${totalPages}`,
                    margin,
                    pageH - 8
                );
            }

            doc.save(`${title.replace(/\s+/g, "_")}_${Date.now()}.pdf`);
        } catch (error) {
            console.error("PDF Export failed:", error);
        } finally {
            setIsExporting(false);
        }
    };

    return (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 md:p-8 bg-black/80 backdrop-blur-sm animate-in fade-in duration-300">
            <div className="relative w-full max-w-5xl h-[90vh] bg-[#16211E] border border-[#D4AF37]/30 rounded-2xl shadow-2xl flex flex-col overflow-hidden">

                {/* Toolbar */}
                <div className="flex items-center justify-between p-4 border-b border-[#D4AF37]/20 bg-[#0D1117]">
                    <div className="flex items-center gap-3">
                        <div className="p-2 bg-[#D4AF37]/10 rounded-lg">
                            <FileText className="w-5 h-5 text-[#D4AF37]" />
                        </div>
                        <div>
                            <h3 className="font-serif font-bold text-lg text-[#E6E6E6]">{title}</h3>
                            <p className="text-[10px] text-[#9CA3AF] uppercase tracking-widest font-sans">
                                Source: {agentName} · Generated Template
                            </p>
                        </div>
                    </div>

                    <div className="flex items-center gap-2">
                        <div className="hidden md:flex items-center bg-[#0D1117] border border-[#D4AF37]/20 rounded-lg p-1 mr-4">
                            <button onClick={() => setZoom(Math.max(0.5, zoom - 0.1))} className="p-1.5 hover:bg-[#16211E] rounded text-[#9CA3AF] transition-colors"><ZoomOut className="w-4 h-4" /></button>
                            <span className="text-xs px-2 text-[#D4AF37] min-w-[3rem] text-center">{Math.round(zoom * 100)}%</span>
                            <button onClick={() => setZoom(Math.min(2, zoom + 0.1))} className="p-1.5 hover:bg-[#16211E] rounded text-[#9CA3AF] transition-colors"><ZoomIn className="w-4 h-4" /></button>
                        </div>

                        <button
                            onClick={handleExportPDF}
                            disabled={isExporting}
                            className="flex items-center gap-2 bg-[#E65100] hover:bg-[#E65100]/90 text-[#E6E6E6] px-4 py-2 rounded-lg text-sm font-semibold transition-all hover:shadow-lg hover:shadow-[#E65100]/20 disabled:opacity-50"
                        >
                            {isExporting ? <span className="animate-spin border-2 border-white/30 border-t-white rounded-full w-4 h-4" /> : <Download className="w-4 h-4" />}
                            {isExporting ? "Branding..." : "Export Premium PDF"}
                        </button>

                        <button
                            onClick={onClose}
                            className="p-2 text-[#9CA3AF] hover:text-[#E6E6E6] hover:bg-[#EF4444]/10 rounded-lg transition-all"
                        >
                            <X className="w-6 h-6" />
                        </button>
                    </div>
                </div>

                {/* Scrollable Document Area */}
                <div className="flex-1 overflow-auto p-4 md:p-12 bg-[#0D1117]/50 custom-scrollbar">
                    <div
                        style={{ transform: `scale(${zoom})`, transformOrigin: 'top center', marginBottom: '100px' }}
                        className="transition-transform duration-200"
                    >
                        {/* The Actual Document - Printable Container */}
                        <div
                            ref={docRef}
                            className="mx-auto w-full max-w-[800px] bg-[#0D1117] border border-[#D4AF37]/10 p-12 shadow-2xl relative overflow-hidden text-[#E6E6E6] min-h-[1000px]"
                        >
                            {/* Subtle Watermark/Branding */}
                            <div className="absolute top-0 right-0 p-8 opacity-5">
                                <h1 className="font-serif text-6xl font-black text-[#D4AF37]">SUTRADHAR</h1>
                            </div>

                            {/* Document Header */}
                            <div className="flex justify-between items-start mb-12 border-b-2 border-[#D4AF37]/30 pb-8">
                                <div>
                                    <div className="flex items-center gap-2 mb-4">
                                        <div className="w-10 h-10 bg-[#E65100] rounded-lg flex items-center justify-center">
                                            <span className="text-[#E6E6E6] font-serif text-xl font-bold">S</span>
                                        </div>
                                        <span className="font-serif text-2xl font-black text-[#D4AF37] tracking-tighter">SUTRADHAR.AI</span>
                                    </div>
                                    <div className="space-y-1">
                                        <p className="text-xs text-[#9CA3AF] uppercase font-bold tracking-widest">Official Document</p>
                                        <h2 className="text-3xl font-serif font-bold text-[#E6E6E6] leading-tight">{title}</h2>
                                    </div>
                                </div>
                                <div className="text-right space-y-2">
                                    <div className="bg-[#16211E] p-4 rounded-xl border border-[#D4AF37]/20 inline-block shadow-inner">
                                        <p className="text-[10px] text-[#D4AF37] uppercase font-bold mb-1">Orchestrated By</p>
                                        <p className="text-sm font-serif font-bold text-[#E6E6E6]">{agentName}</p>
                                        <p className="text-[10px] text-[#9CA3AF]">{agentRole}</p>
                                    </div>
                                </div>
                            </div>

                            {/* Dynamic Content Body */}
                            <div className="prose prose-invert max-w-none prose-headings:font-serif prose-headings:text-[#D4AF37] prose-p:font-sans prose-p:text-[#E6E6E6]/90 prose-strong:text-[#E65100]">
                                <MarkdownOutput content={content} />
                            </div>

                            {/* Document Footer */}
                            <div className="mt-20 pt-8 border-t border-[#D4AF37]/20 flex justify-between items-end">
                                <div className="space-y-1">
                                    <p className="text-[10px] text-[#9CA3AF] uppercase font-bold flex items-center gap-1">
                                        <Clock className="w-3 h-3" />
                                        Generated On
                                    </p>
                                    <p className="text-xs text-[#E6E6E6]">{new Date(timestamp).toLocaleString('en-US', { dateStyle: 'long', timeStyle: 'medium' })}</p>
                                </div>
                                <div className="text-right">
                                    <p className="text-[10px] text-[#D4AF37] italic font-serif opacity-60">Verified & Orchestrated by Sutradhar AI Intelligence Pipeline</p>
                                    <p className="text-[9px] text-[#6B7280] font-sans">© 2026 Sutradhar.AI. All Rights Reserved.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Footer info bar */}
                <div className="p-3 bg-[#0D1117] border-t border-[#D4AF37]/10 flex justify-center text-[10px] text-[#6B7280]">
                    <span className="flex items-center gap-1">
                        <Printer className="w-3 h-3" />
                        Premium Document Preview Mode · Pixel-Perfect Layout · High Fidelity PDF Export
                    </span>
                </div>
            </div>
        </div>
    );
}
